name: Build

on:
  pull_request:
  push:
    branches:
      - master
      - release
      - dev
      - minimal

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: 'iamssen/couchdb-github-action@master'
        with:
          couchdb-version: '3.1'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm test
        env:
          CLOUDANT_USER: ${{ secrets.CLOUDANT_USER}}
          CLOUDANT_PASS: ${{ secrets.CLOUDANT_PASS}}

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/release'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN}}
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
